[package]
name = "gl"
version = "0.1.0"
authors = ["Bas van Schoonhoven"]
edition = "2018"

[build-dependencies]
gl_generator = { version = "0.14.0", features = ["unstable_generator_utils"] }

[features]
debug = []